web_scraping:
  start_page: https://life.com.ua
  product_name_selector: ".product-title"
  product_price_selector: ".product-price__item"
  product_description_selector: ".product-description"
  product_image_selector: ".gallery__link"