web_scraping:
  start_page: http://books.toscrape.com/catalogue/category/books_1/index.html

  product_name_selector: "h3 a"
  product_price_selector: "p.price_color"
  product_description_selector: "p"
  product_image_selector: "img"